/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_swrh_jnyikes_JNyIkes */

#ifndef _Included_com_github_swrh_jnyikes_JNyIkes
#define _Included_com_github_swrh_jnyikes_JNyIkes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_swrh_jnyikes_JNyIkes
 * Method:    j2n
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_github_swrh_jnyikes_JNyIkes_j2n
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
